---
kind: pipeline
name: grav-1.6

steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: 1.6/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: mwalbeck/getgrav
      tags:
        - latest
        - "1.6"
        - "1.6.24"

---
kind: pipeline
name: grav-1.7

steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: 1.7/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: mwalbeck/getgrav
      tags:
        - "1.7-rc"
        - "1.7.0-rc8"
