---
kind: pipeline
name: grav_1.6

steps:
  - name: determine tags
    image: bash
    environment:
      APP: "GRAV"
      DIR: "1.6/"
      CUSTOM_TAGS: "latest,"
    commands:
      - apk add --no-cache grep
      - VER=$(grep "ENV $${APP}_VERSION" $${DIR:-}Dockerfile)
      - VER=$${VER##* }
      - PRE=$${VER#*-}
      - VER=$${VER%-*}
      - TAGS="$${CUSTOM_TAGS:-}"
      - if [ "$PRE" = "$VER" ]; then PRE=""; else PRE="-$PRE"; fi;
      - TAGS="$TAGS$VER$PRE,"
      - VER=$${VER%.*}
      - TAGS="$TAGS$VER$PRE"
      - echo -n $TAGS > .tags
      - echo $TAGS

  - name: build and publish
    image: plugins/docker
    settings:
      dockerfile: 1.6/Dockerfile
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: mwalbeck/getgrav

  - name: notify
    image: plugins/matrix
    settings:
      homeserver: https://matrix.mwalbeck.org
      roomid:
        from_secret: matrix_roomid
      username:
        from_secret: matrix_username
      password:
        from_secret: matrix_password
    when:
      status:
        - success
        - failure

trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
name: test_1.6

steps:
  - name: build test
    image: plugins/docker
    settings:
      dockerfile: 1.6/Dockerfile
      repo: mwalbeck/getgrav
      dry_run: true

trigger:
  event:
    - pull_request

---
kind: pipeline
name: grav_1.7

steps:
  - name: determine tags
    image: bash
    environment:
      APP: "GRAV"
      DIR: "1.7/"
      CUSTOM_TAGS: ""
    commands:
      - apk add --no-cache grep
      - VER=$(grep "ENV $${APP}_VERSION" $${DIR:-}Dockerfile)
      - VER=$${VER##* }
      - PRE=$${VER#*-}
      - VER=$${VER%-*}
      - TAGS="$${CUSTOM_TAGS:-}"
      - if [ "$PRE" = "$VER" ]; then PRE=""; else PRE="-$PRE"; fi;
      - TAGS="$TAGS$VER$PRE,"
      - VER=$${VER%.*}
      - TAGS="$TAGS$VER$PRE"
      - echo -n $TAGS > .tags
      - echo $TAGS

  - name: build and publish
    image: plugins/docker
    settings:
      dockerfile: 1.7/Dockerfile
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: mwalbeck/getgrav

  - name: notify
    image: plugins/matrix
    settings:
      homeserver: https://matrix.mwalbeck.org
      roomid:
        from_secret: matrix_roomid
      username:
        from_secret: matrix_username
      password:
        from_secret: matrix_password
    when:
      status:
        - success
        - failure

trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
name: test_1.7

steps:
  - name: build test
    image: plugins/docker
    settings:
      dockerfile: 1.7/Dockerfile
      repo: mwalbeck/getgrav
      dry_run: true

trigger:
  event:
    - pull_request
