name: Test

on: pull_request

jobs:
  lint:
    if: github.ref != 'refs/heads/renovate/*'
    runs-on: docker
    steps:
      - uses: actions/checkout@v5
      - uses: https://github.com/hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: ./1.7/Dockerfile
      - uses: https://github.com/hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: ./1.7/Dockerfile.prod
      - uses: https://github.com/ludeeus/action-shellcheck@2.0.0

  grav1_7:
    runs-on: dind
    steps:
      - uses: actions/checkout@v5
      - name: Get docker tags
        id: tags
        shell: sh
        env:
          VERSION_TYPE: "docker_env"
          APP_NAME: "GRAV"
          DOCKERFILE_PATH: "1.7/Dockerfile"
          INCLUDE_MAJOR: "no"
          CUSTOM_TAGS: "latest"
          IMAGE_NAME: "mwalbeck/getgrav"
        run: |
          determine-docker-tags
          dockerd &
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Test build
        uses: https://github.com/docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.tags.outputs.tags }}
          file: ./1.7/Dockerfile

  grav1_7_prod:
    runs-on: dind
    steps:
      - uses: actions/checkout@v5
      - name: Get docker tags
        id: tags
        shell: sh
        env:
          VERSION_TYPE: "docker_env"
          APP_NAME: "GRAV"
          APP_ENV: "prod"
          DOCKERFILE_PATH: "1.7/Dockerfile.prod"
          INCLUDE_MAJOR: "no"
          CUSTOM_TAGS: "latest-prod"
          IMAGE_NAME: "mwalbeck/getgrav"
        run: |
          determine-docker-tags
          dockerd &
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Test build
        uses: https://github.com/docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.tags.outputs.tags }}
          file: ./1.7/Dockerfile.prod
