name: ci
on: [push]
jobs:
  multi:
    runs-on: ubuntu-latest
    env:
        APP_VERSION: 0.0.1
    steps:
      - 
        name: identify
        run: echo ${{ env.APP_VERSION }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./1.6/Dockerfile
          build-args: APP_VERSION=${{ env.APP_VERSION }}
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_REPO }}:1.6

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./1.7/Dockerfile
          build-args: APP_VERSION=${{ env.APP_VERSION }}
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_REPO }}:1.7
